name: docker pr

on:
  push:
    branches:
      - "**"
      - '!main'

env:
  IMAGE_FQDN: ghcr.io/eugenmayer/kontextwork-converter

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      # push only on main
      - name: Build production
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          target: production
          push: false
          tags: | 
            ${{ env.IMAGE_FQDN }}:latest
      - name: Build dev
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          target: development
          push: false
          tags: |
            ${{ env.IMAGE_FQDN }}:latest
